version: 2

sources:
  - name: library
    schema: library_loans
    tables:
      - name: books_factual
      - name: books_fictional
      - name: loans
      - name: members

seeds:
  - name: solution

models: 
  - name: customer_withdrawals
    columns:
      - name: member_name
        tests:
          - no_digits_in_column
  - name: customers_with_late_fees
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('solution')
    columns:
      - name: member_name
        tests:
          - no_digits_in_column
  - name: stg_books
    columns: 
      - name: book_id 
        data_tests:
          - not_null
          - unique
  - name: stg_members
    columns: 
        - name: member_id 
          data_tests: 
            - not_null
        - name: membership_tier
          data_tests:
            - accepted_values:
                values: ["Bronze", "Silver", "Gold"]
  - name: stg_loans
    columns:
      - name: loan_id
        tests:
          - not_null
      - name: book_id
        tests:
          - relationships:
              to: ref('stg_books')
              field: book_id
      - name: member_id
        tests:
          - relationships:
              to: ref('stg_members')
              field: member_id
              
