version: 2

sources:
  - name: lego
    database: DBT_COURSE
    schema: LEGO
    tables:
      - name: colors
        description: dimension table of lego colors
        columns:
          - name: id
            description: primary key and unique identifier of each color
            tests:
              - not_null
              - unique
          - name: name
            description: the name of the color
            tests:
              - not_null
              - unique
          - name: RGB
            description: the hex value of the color
            tests:
              - not_null
          - name: is_trans
            tests:
              - accepted_values:
                  values: ["TRUE", "FALSE"]

      - name: inventories
        description: dimension table of what we currently stock
        columns:
          - name: id
            description: primary key
            tests:
              - unique
              - not_null
          - name: version
            description: the version of each set we carry
            tests:
              - not_null
          - name: set_num
            description: foreign key and the set identifier
            tests:
              - not_null
              - relationships:
                  to: source('lego','sets')
                  field: set_num

      - name: inventory_parts
        description: the parts within each set we stock
        columns:
          - name: inventory_id
            description: foreign key to inventories table
            tests:
              - not_null
              - relationships:
                  to: source('lego','inventories')
                  field: id
          - name: part_num
            description: foreign key to parts table - not behaving properly
            tests:
              - not_null
          - name: color_id
            description: foreign key to colors table
            tests:
              - not_null
              - relationships:
                  to: source('lego','colors')
                  field: id
          - name: quantity
            description: how many of that part is in the set
            tests:
              - not_null
          - name: is_spare
            description: boolean if the part is spare
            tests:
              - not_null
              - accepted_values:
                  values: ["TRUE", "FALSE"]

      - name: inventory_sets
        description: dimension table of sets and how many we stock
        columns:
          - name: inventory_id
            description: foreign key to inventories
            tests:
              - not_null
              - relationships:
                  to: source('lego','inventories')
                  field: id
          - name: set_num
            description: foreign key from sets
            tests:
              - not_null
              - relationships:
                  to: source('lego','sets')
                  field: set_num
          - name: quantity
            description: how many of each set we hold

      - name: parts
        description: dimension table of lego parts
        columns:
          - name: part_num
            description: primary key and unique identifier of each part
            tests:
              - not_null
              - unique
          - name: name
            description: the name of the part
            tests:
              - not_null
          - name: part_cat_id
            description: foreign key from part_categories table
            tests:
              - not_null
              - relationships:
                  to: source('lego','part_categories')
                  field: id

      - name: part_categories
        description: dimension table combining parts into different categories
        columns:
          - name: id
            description: primary key
            tests:
              - unique
              - not_null
          - name: name
            description: the part category name
            tests:
              - not_null

      - name: sets
        description: dimension table of all lego sets
        columns:
          - name: set_num
            description: primary key
            tests:
              - not_null
              - unique
          - name: name
            description: the name of the set
            tests:
              - not_null
          - name: year
            description: the year the set was released
            tests:
              - not_null
          - name: theme_id
            description: foreign key from themes
            tests:
              - not_null
              - relationships:
                  to: source('lego','themes')
                  field: id
          - name: num_parts
            description: the number of parts in each set
            tests:
              - not_null

      - name: themes
        description: dimension table grouping sets into different themes
        columns:
          - name: id
            description: primary key
            tests:
              - not_null
              - unique
          - name: name
            description: the name of the theme
            tests:
              - not_null
          - name: parent_id
            description: if a theme is a sub-theme, the id of its parent
            tests:
              - relationships:
                  to: source('lego','themes')
                  field: id
